SLStudio.Utils.RemoveHighlighting(get_param('lab3_p9', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_lab3_p9', 'handle'));
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/Relational Operator', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Logical Operator', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Math Function', 1, 1, '');
annotate_port('lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Math Function', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product1', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Min_stage1', 0, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Min_stage1', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/MinMax_stage1', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Chart/Chart', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Chart/Chart/Chart', 1, 1, '');
annotate_port('lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Chart', 1, 1, '');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter/HDL Counter', 1, 1, '');
