open_system('gm_lab3_p9');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal', 0, 1, 'cp : 17.168 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/Relational Operator', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/Relational Operator', 0, 1, 'cp : 19.935 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter', 1, 1, 'cp : 22.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Logical Operator', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/Logical Operator', 0, 1, 'cp : 21.856 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product', 0, 1, 'cp : 17.168 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product1', 'user1');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Product1', 0, 1, 'cp : 8.636 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Min_stage1', 'user2');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/Normalize Signal/Min_stage1', 0, 1, 'cp : 17.168 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter/HDL Counter', 'user1');
annotate_port('gm_lab3_p9/dataplane/Avalon Data Processing/Left Channel Processing/Signal Energy Monitor/LED_Driver/LED_persistence_control/HDL Counter/HDL Counter', 1, 1, 'cp : 22.914 ns');
