-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\lab3_p9\dataplane_src_dataplane_pkg.vhd
-- Created: 2020-04-17 18:48:36
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE dataplane_src_dataplane_pkg IS
  TYPE T_state_type_is_Chart IS (IN_LED_off, IN_LED_on);
END dataplane_src_dataplane_pkg;

