
/**
 * This is the loop class to test different loop methods.
 * 
 * @author Joshua Harthan
 * @version 24Oct2016
 */
public class Loop
{

    public void loop1(int lowerBound, int upperBound, int increment)
   { 
       System.out.println("Loop 1 output (lb = " + lowerBound + ", ub = " + upperBound + ", incr = " + increment + "):");
       for(int i = lowerBound ; i <= upperBound ; i += increment)   //start at lowerbound, until lowerbound is less than or equal to upperbound, increment by one
        {  
            System.out.println(i);  //print out the number
        }
       System.out.println("---------------------------------------------------");
    }

    public void loop2(int lowerBound, int upperBound, int increment)//parameters for loop 2
    {
        System.out.println("Loop 2 output (lb = " + lowerBound + ", ub = " + upperBound + ", incr = " + increment + "):");
        while (lowerBound <= upperBound)  //while loop for when the number is less than the highest possible number given
        {
            System.out.println(lowerBound); // print out the value of the number
            lowerBound += increment;    //increment the number by the number given  
        }
        System.out.println("---------------------------------------------------");
    }
    
    public void loop3()
    {
        System.out.println("Loop 3 output:");
        String a = "abcdefghijklmnopqrstuvwxyz";    //local variable of the alphabet
        for(int i = 1 ; i <= 26; i++)   //loop for beginning at 1, stopping at the last letter at 26, increment by 1
        {
            System.out.println(a.substring(0, i));  //substring from the beginning of the alphabet to the end, adding new letter each line 
        }
        System.out.println("---------------------------------------------------");
    }
    
    public static void loop4(int value)
    {
        System.out.println("Loop 4 output:");
        int numGen = 0; //the number of times the number is to be generated
        for (int i = 0 ; i <= 10 ; i++) //starting at 0, looping the number 10 times
        {
            int randNum = (int) (10 * Math.random() + 1);   //generate a random number between 1 and 10
            if (randNum == value)   //if the number generated equals the value
            {
                numGen++;   //increment the number of times value has been generated by one
            }
        }
        System.out.println(value + " was found " + numGen + " time(s).");
        System.out.println("---------------------------------------------------");       
    }
    
    public static void loop5(int value)
    {
        int num = 0;    //number of times the value has been generated
        int numTimes = 0; //number of times generated
        while (num < 5) //while the number of times generated is less than five
        {
            int numGenerated = (int) ((10 * Math.random() + 1)); //generate a random number between 1 and 10
            numTimes++; //increment the number of times generated by one for each random number
            if (numGenerated == value) //if the random number generated equals the value
            {
                num++;  //increment the number of times the value has been generated by one
            }
        }   
        System.out.println("Loop 5 Output:");
        System.out.println("It took " + numTimes + " iterations to generate " + value + " five times.");
        System.out.println("---------------------------------------------------");
    }
    
}

