#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_COMPONENT_NAME onchip_memory
#define ONCHIP_MEMORY_BASE 0x0
#define ONCHIP_MEMORY_SPAN 65536
#define ONCHIP_MEMORY_END 0xffff
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE soc_system_onchip_memory
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID NONE
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 65536
#define ONCHIP_MEMORY_WRITABLE 1
#define ONCHIP_MEMORY_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory

/*
 * Macros for device 'Qsys_alu_0', class 'Qsys_alu'
 * The macros are prefixed with 'QSYS_ALU_0_'.
 * The prefix is the slave descriptor.
 */
#define QSYS_ALU_0_COMPONENT_TYPE Qsys_alu
#define QSYS_ALU_0_COMPONENT_NAME Qsys_alu_0
#define QSYS_ALU_0_BASE 0x0
#define QSYS_ALU_0_SPAN 32
#define QSYS_ALU_0_END 0x1f

/*
 * Macros for device 'SystemID', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSTEMID_'.
 * The prefix is the slave descriptor.
 */
#define SYSTEMID_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSTEMID_COMPONENT_NAME SystemID
#define SYSTEMID_BASE 0x20
#define SYSTEMID_SPAN 8
#define SYSTEMID_END 0x27
#define SYSTEMID_ID 2899645186
#define SYSTEMID_TIMESTAMP 1575579111

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x28
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x2f
#define JTAG_UART_IRQ 0
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_H_ */
