#ifndef _ALTERA_JTAG_MM1_H_
#define _ALTERA_JTAG_MM1_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'jtag_mm1' and devices
 * connected to the following master:
 *   master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'Qsys_alu_0', class 'Qsys_alu'
 * The macros are prefixed with 'QSYS_ALU_0_'.
 * The prefix is the slave descriptor.
 */
#define QSYS_ALU_0_COMPONENT_TYPE Qsys_alu
#define QSYS_ALU_0_COMPONENT_NAME Qsys_alu_0
#define QSYS_ALU_0_BASE 0x0
#define QSYS_ALU_0_SPAN 32
#define QSYS_ALU_0_END 0x1f


#endif /* _ALTERA_JTAG_MM1_H_ */
