-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_final\hdlsrc\lab3_p12\dataplane_src_Sound_Effects_block.vhd
-- Created: 2020-05-07 13:40:35
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dataplane_src_Sound_Effects_block
-- Source Path: lab3_p12/dataplane/Avalon Data Processing/Right Channel Processing/Sound Effects
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dataplane_src_Sound_Effects_block IS
  PORT( Data_In                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        Data_Out                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
        );
END dataplane_src_Sound_Effects_block;


ARCHITECTURE rtl OF dataplane_src_Sound_Effects_block IS

BEGIN
  Data_Out <= Data_In;

END rtl;

